#include "popup.h"
#include <M5Unified.h>
void showWifiDisconnectedPopup(const AppState &state){
    M5.Display.setTextDatum(MC_DATUM);
    M5.Display.fillRect(WIFI_POPUP_STARTX, WIFI_POPUP_STARTY, WIFI_POPUP_WIDTH, WIFI_POPUP_HEIGHT, TFT_WHITE);
    M5.Display.drawRect(WIFI_POPUP_STARTX, WIFI_POPUP_STARTY, WIFI_POPUP_WIDTH, WIFI_POPUP_HEIGHT, TFT_BLACK);
    M5.Display.drawString("ネットワークがありません",WIFI_POPUP_STARTX + WIFI_POPUP_WIDTH/2, WIFI_POPUP_STARTY + WIFI_POPUP_HEIGHT/2);
}

void showLoadingPopup(const AppState &state){
    M5.Display.setTextDatum(MC_DATUM);
    M5.Display.fillRect(LOADING_POPUP_STARTX, LOADING_POPUP_STARTY, LOADING_POPUP_WIDTH, LOADING_POPUP_HEIGHT, TFT_WHITE);
    M5.Display.drawRect(LOADING_POPUP_STARTX, LOADING_POPUP_STARTY, LOADING_POPUP_WIDTH, LOADING_POPUP_HEIGHT, TFT_BLACK);
    M5.Display.drawString("ロード中・・・",LOADING_POPUP_STARTX + LOADING_POPUP_WIDTH/2, LOADING_POPUP_STARTY + LOADING_POPUP_HEIGHT/2);
}